mywebsite/account/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^register/$', views.register_view, name="register"),
	url(r'^login/$', views.login_view, name="login"),
	url(r'^logout/$', views.logout_view, name="logout"),
	url(r'^profile/(?P<id>\d+)/$', views.profile_view, name="profile"),
	url(r'^delete/(?P<id>\d+)/(?P<proid>\d+)/$', views.delete_event, name="delete"),
]

mywebsite/events/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[

		url(r'^$', views.branch, name="events"),
		url(r'^details/(?P<id>\d+)/$', views.event_details , name='details'),
		url(r'^register/$', views.register_view , name="register"),
		
]

mywebsite/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.home,name="home")
]

mywebsite/mywebsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^about/',include('about_us.urls',namespace="about")),
    url(r'^notifications/',include('notification.urls',namespace="notification")),
    url(r'^events/',include('events.urls',namespace="events")),
    url(r'^account/',include('account.urls',namespace="account")),
    url(r'^contact/',include('contact.urls',namespace="contact")),
    url(r'^gallery/',include('gallery.urls',namespace="gallery")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mywebsite/events/models.py
from django.db import models
from account.models import Profile

class Branch(models.Model):
	branch=models.CharField(max_length=200)
	bimage=models.ImageField(null=True)
	def __str__(self):
		return self.branch

class Events(models.Model):
	event=models.CharField(max_length=200)
	branch=models.ForeignKey(Branch)
	def __str__(self):
		return self.event
		
class Coordinator(models.Model):
	event=models.ForeignKey(Events)
	cname=models.CharField(max_length=200)
	cmobile=models.IntegerField(null=True)
	cimage=models.ImageField(null=True)
	cemail=models.EmailField(max_length=200,null=True)
	
	def __str__(self):
		return self.cname

class Participant(models.Model):
	events = models.ForeignKey(Events, on_delete=models.CASCADE, null=True)
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
	team_name = models.CharField(max_length=30,  null=True)
	events_name = models.CharField(max_length=30,  null=True)
	member2 = models.CharField(max_length=50, null=True)
	member3 = models.CharField(max_length=50,  null=True)
	member4 = models.CharField(max_length=50,  null=True)
	member5 = models.CharField(max_length=50,  null=True)

	def __str__(self):
		return self.team_name

mywebsite/events/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import  Branch,Events,Coordinator,Participant

# Create your views here.

def branch(request):
	branch_all=Branch.objects.all()
	event_all=Events.objects.all()
     
     # ALL ELEMENTS FROM THE DATABASE TAKEN BY MODULE

	outer_event=dict()
	for b in branch_all:
		e=event_all.filter(branch=b)
		outer_event[b]=e

	context={
	    	 'outer_event':outer_event,
	    	 'branch_all':branch_all
	        }
	return render(request,'events.html',context)



def event_details(request,id=None):
	coord = Coordinator.objects.filter(event_id=id)
	#eve = Events.objects.get(id=id)
	events = get_object_or_404(Events,id=id)
	page=events.event.lower()
	page='events/'+page+'.html'
	context = {
	      'eve':events.event.upper(),
	      'events':events,
	     'coord':coord
	}

	return render(request,page,context)


####.....REGISTERATION  FOR EVENTS.....##### 


def register_view(request):

	team_name = request.GET['team_name']
	member2 = request.GET['member2']
	member3 = request.GET['member3']
	member4 = request.GET['member4']
	member5 = request.GET['member5']
	event_id = request.GET['event_id']
	profile_id = request.GET['profile_id']
	events_name = request.GET['events_name']

	t=Participant.objects.filter(team_name=team_name)
	if len(t):
		return render(request,'events.html',{'msg':'Team name already taken'})

	t=Participant.objects.filter(profile=profile_id, events_name=events_name)
	if len(t):
		return render(request,'events.html',{'msg':'You are already participated in this event'})
	part=Participant(

		team_name=team_name,
		events_name=events_name,
		member2=member2,
		member3=member3,
		member4=member4,
		member5=member5,
		events_id=event_id,
		profile_id=profile_id,


		)
	part.save()
	return HttpResponseRedirect(reverse('events:events'))
	

mywebsite/templates/events/air fray.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/algosense.html
{% extends 'base_events.html' %}
{% load static %}
 {% block head %}
  
  <style type="text/css">
    li{
      font-size:15px;
    }
  </style>

 {% endblock %} 


{% block desc %}
    
        <ul class="list-unstyled">
          <li>Coding is a combination of artistry and engineering. So gear up everyone for the befalling event.</li>
          <li>“ALGOSENSE”, a bewildering platform to showcase your competency and mutation in fabricating the algorithm and programming.</li>
          <li>The event "ALGOSENSE" provides you with the opportunity to show and enhance your skills on Languages like “C”,”Java”,”Python” &”C++”.</li>
        </ul>
        <br>
        <h2>Judging Criteria</h2>
        <ul class="list-unstyled">
          <li>Accuracy of your output.</li>
          <li>Complexity of algorithm.</li>
          <li>Problem Solving Approach.</li>

        </ul>
{% endblock  %}


{% block rules %}
        <ul class="list-unstyled">
          <li>Coding is a combination of artistry and engineering. So gear up everyone for the befalling event.</li>
          <li>“ALGOSENSE”, a bewildering platform to showcase your competency and mutation in fabricating the algorithm and programming.</li>
          <li>The event "ALGOSENSE" provides you with the opportunity to show and enhance your skills on Languages like “C”,”Java”,”Python” &”C++”.</li>
        </ul>
        <br>
        <h2>Judging Criteria</h2>
        <ul class="list-unstyled">
          <li>Accuracy of your output.</li>
          <li>Complexity of algorithm.</li>
          <li>Problem Solving Approach.</li>
        </ul>

{% endblock %}

{% block reg %}

   {% if user.is_authenticated %}

      <center><p style="color:red;">{{ msg }}</p></center>

      <h3>Team size: 2, Minimum: 1, Maximum: 2</h3>
      <p>You are first member</p>
      <form  action="{% url 'events:register' %}" method="get">
      
      <label>Team Name:</label>
      <input class="form-control" type="text" name="team_name" placeholder="Enter Team Name" required="required" autocomplete="off">
      <label>Member 2 (Optional):</label>
      <input class="form-control" type="text" name="member2" placeholder="Enter 2nd member name" value="" autocomplete="off">
      <input class="form-control" type="hidden" name="member3" placeholder="Enter 3rd member name" value="">
      <input class="form-control" type="hidden" name="member4" placeholder="Enter 4th member name" value="">
      <input class="form-control" type="hidden" name="member5" placeholder="Enter 5th member name" value="">


      <input type="hidden" name="event_id" value="{{ events.id }}">
      <input type="hidden" name="events_name" value="{{ events.event }}">
      <input type="hidden" name="profile_id" value="{{ user.profile.id }}"><br>

      <center>
        <input class="btn btn-default btn-success" type="submit" value="Submit">
        <input class="btn btn-default btn-info" type="reset" value="Reset">
      </center>

    </form><br><br>

  {% else %}

     <h2>You are not logged in.</h2><br>
     <button class="btn btn-default btn-info"><a href="{% url 'account:login' %}" style="color:black">Click Here To Login /Register</a></button>
     <br>


  {% endif %}




{% endblock %}   

mywebsite/templates/events/appmania.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/bridge-it.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/contrapation.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/digicanava.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/modechx.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/robo race.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/robo soccer.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/sky rc.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/techyshot.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/webbit.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}

mywebsite/templates/events/zumowar.html
{% extends 'base_events.html' %}
{% load static %}



{% block head %}
{% endblock %}


{% block desc %}
{% endblock %}


{% block rules %}
{% endblock %}


{% block coord %}
{% endblock %}