mywebsite/contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[

		url(r'^$', views.contact, name="contact"),
		url(r'^feed/$', views.feed , name="feed"),
		
]

mywebsite/events/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[

		url(r'^$', views.branch, name="events"),
		url(r'^details/(?P<id>\d+)/$', views.event_details , name='details'),
		url(r'^register/$', views.register_view , name="register"),
		
]

mywebsite/gallery/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[

		url(r'^$',views.gallery_view,name='gallery'),


]

mywebsite/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.home,name="home")
]

mywebsite/mywebsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^about/',include('about_us.urls',namespace="about")),
    url(r'^notifications/',include('notification.urls',namespace="notification")),
    url(r'^events/',include('events.urls',namespace="events")),
    url(r'^account/',include('account.urls',namespace="account")),
    url(r'^contact/',include('contact.urls',namespace="contact")),
    url(r'^gallery/',include('gallery.urls',namespace="gallery")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mywebsite/notification/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.notice,name="notify")
]

mywebsite/contact/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
	name=models.CharField(max_length=30)
	email=models.EmailField()
	feed=models.CharField(max_length=100)

	def __str__(self):
		return self.name

mywebsite/events/models.py
from django.db import models
from account.models import Profile

class Branch(models.Model):
	branch=models.CharField(max_length=200)
	bimage=models.ImageField(null=True)
	def __str__(self):
		return self.branch

class Events(models.Model):
	event=models.CharField(max_length=200)
	branch=models.ForeignKey(Branch)
	def __str__(self):
		return self.event
		
class Coordinator(models.Model):
	event=models.ForeignKey(Events)
	cname=models.CharField(max_length=200)
	cmobile=models.IntegerField(null=True)
	cimage=models.ImageField(null=True)
	cemail=models.EmailField(max_length=200,null=True)
	
	def __str__(self):
		return self.cname

class Participant(models.Model):
	events = models.ForeignKey(Events, on_delete=models.CASCADE, null=True)
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
	team_name = models.CharField(max_length=30,  null=True)
	events_name = models.CharField(max_length=30,  null=True)
	member2 = models.CharField(max_length=50, null=True)
	member3 = models.CharField(max_length=50,  null=True)
	member4 = models.CharField(max_length=50,  null=True)
	member5 = models.CharField(max_length=50,  null=True)

	def __str__(self):
		return self.team_name

mywebsite/gallery/models.py
from django.db import models

# Create your models here.

class gallery(models.Model):
	imgid=models.CharField(max_length=4)
	image=models.ImageField(upload_to='images/gallery', blank=True)

	def __str__(self):
		return self.imgid

mywebsite/contact/forms.py
from django import forms

class Feedbackform(forms.Form):

	name=forms.CharField(label='Your Name:',
		widget=forms.TextInput(
			attrs={
				'class':'form-control',
				'placeholder':'Name Please!'

			}
		)
		
	)


	email=forms.CharField(label="Your Email Id:",
		widget=forms.TextInput(
			attrs={
				'class':'form-control',
				'placeholder':'Email Id '

			}
		)
		
	)


	feed=forms.CharField(label="Write your feed:",
		widget=forms.TextInput(
			attrs={
				'class':'form-control',
				'placeholder':'Feedback'

			}
		)
		
	)

		

mywebsite/contact/views.py
from django.shortcuts import render
from .models import Feedback
from .forms import Feedbackform

# Create your views here.

def contact(request):
	form=Feedbackform()
	return render(request,'contact.html',{'form':form})

def feed(request):

	name=request.GET['name']
	email=request.GET['email']
	feed=request.GET['feed']

	f=Feedback(

		name=name,
		email=email,
		feed=feed,

		)
	f.save()

	form=Feedbackform()
	return render(request,'contact.html',{'form':forms})

mywebsite/events/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import  Branch,Events,Coordinator,Participant

# Create your views here.

def branch(request):
	branch_all=Branch.objects.all()
	event_all=Events.objects.all()
     
     # ALL ELEMENTS FROM THE DATABASE TAKEN BY MODULE

	outer_event=dict()
	for b in branch_all:
		e=event_all.filter(branch=b)
		outer_event[b]=e

	context={
	    	 'outer_event':outer_event,
	    	 'branch_all':branch_all
	        }
	return render(request,'events.html',context)



def event_details(request,id=None):
	coord = Coordinator.objects.filter(event_id=id)
	#eve = Events.objects.get(id=id)
	events = get_object_or_404(Events,id=id)
	page=events.event.lower()
	page='events/'+page+'.html'
	context = {
	      'eve':events.event.upper(),
	      'events':events,
	     'coord':coord
	}

	return render(request,page,context)


####.....REGISTERATION  FOR EVENTS.....##### 


def register_view(request):

	team_name = request.GET['team_name']
	member2 = request.GET['member2']
	member3 = request.GET['member3']
	member4 = request.GET['member4']
	member5 = request.GET['member5']
	event_id = request.GET['event_id']
	profile_id = request.GET['profile_id']
	events_name = request.GET['events_name']

	t=Participant.objects.filter(team_name=team_name)
	if len(t):
		return render(request,'events.html',{'msg':'Team name already taken'})

	t=Participant.objects.filter(profile=profile_id, events_name=events_name)
	if len(t):
		return render(request,'events.html',{'msg':'You are already participated in this event'})
	part=Participant(

		team_name=team_name,
		events_name=events_name,
		member2=member2,
		member3=member3,
		member4=member4,
		member5=member5,
		events_id=event_id,
		profile_id=profile_id,


		)
	part.save()
	return HttpResponseRedirect(reverse('events:events'))
	

mywebsite/gallery/views.py
from django.shortcuts import render
from .models import gallery

# Create your views here.


def gallery_view(request):
	images=gallery.objects.all()
	return render(request,'gallery.html',{'images':images})

mywebsite/templates/about.html
{% extends 'base.html' %}
{% block head %}
{% load static %}

<style type="text/css">
           #notes{
                border:1px solid yellow;
                border-left:6px solid yellow;
            } 
          .panel-height {
               height:100%; / change according to your requirement/
            }
            
            .underline_text {
                text-align: center;
                font-size:5.7vw;
                color:aquamarine;
                font-family: cursive;
            }
            p{
              font-family: serif;
              font-size: 20px;
              overflow: auto;
            }
            th{
              font-size: 2.8vw;
              font-family: cursive;
            }
 </style> 

 <script type="text/javascript" src=" {% static 'js/about.js' %}"></script>

{% endblock %}

{% block body %}
     <h1 class="underline_text">ABOUT US</h1><br><br>
     <div class="container-fluid">
     <div class="row">
      <div class="col-md-10 col-md-offset-1 col-sm-12 ">
        <div class="panel panel-info">
         <div class="panel-body panel-height" style="background-color:white;width:100%">          
              <p>YANTRAGENE is the annual technical festival of FEROZE GANDHI INSTITUTE OF ENGINEERING AND TECHNOLOGY, RAEBARELI. Yantragene was started in the year 2k16.To strengthen the spirit and to further reinforce the role of young minds it has come up with enriching experience of innovation, competition and learning . Yantragene’18 is scheduled for the month of April. Yantragene is entirely managed by students of FGIET. Yantragene is true believer of united we stand divided we fall. The word ‘Yantragene’ is originated from the Sanskrit word Yantra and English word gene. Yantragene comprises of twenty one events of various branch.</p>
            <br><br>
             <table class="table">
                <tr>
                    <th>Events</th>
                    <th>Team Participated</th>
                    <th>Prize Money</th>
                </tr>
                <tr>
                  <center>
                  <td>{{ events }}</td>
                  <td>{{ team_participated }}</td>
                  <td>{{ prize }}</td></center>
                </tr>
               
             </table>
            </div>
         </div>
      </div>       
     </div>
  </div>
   



</div>  
{% endblock %}

mywebsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="icon" href="https://yantragene.co.in/images/minLogo.png" type="image/jpg" sizes="16x16">
  <title>YAΠTΓAGΣΠΣ</title>
  <style type="text/css">
                
                body{
                  background:#110E0B;
                }
              #yantra_icon{
               width:40px;
               height:40px;
              }
  </style>
  {% block head %}
 {% endblock %}
</head>
<body>
    
      <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-header">
          <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <img id="yantra_icon"src="{% static 'images/logo1.png' %}"/>
      </div>
      
         <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class=""><a href="#"></a></li>

          <li><a class="navbar-brand" href="{% url 'home:home' %}" style="font-family:cursive;">YANTRAGENE</a></li>
          <li id="home_nav"><a href="{% url 'home:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
          <li id="event_nav"><a href="{% url 'events:events' %}"><span class="glyphicon glyphicon-flag"></span> Events</a></li>
          <li id="note_nav"><a href="{% url 'notification:notify' %}"><span class="glyphicon glyphicon-bell"></span><span class="badge" style="color:red;">1</span> Notifications</a></li>
          <li id="about_nav"><a href="{% url 'about:about' %}"><span class="  glyphicon glyphicon-info-sign"></span> About Us</a></li>
          <li id="gallery_nav"><a href="{% url 'gallery:gallery' %}"><span class="glyphicon glyphicon-picture" ></span> Gallery</a></li>
          <li id="contact_nav"><a href="{% url 'contact:contact' %}"><span class="glyphicon glyphicon-earphone"></span> Contact Us</a></li>
           


        {% if user.is_authenticated %}
              
              <li id="welcome_nav" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Welcome {{ user.first_name }}<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'account:profile' id=user.profile.id %}">View Profile</a></li>
                <li><a href="{% url 'account:logout' %}">Logout</a></li>
                
              </ul>
            </li>

            {% else %}
              <li id="reg_nav"><a href="{% url 'account:login' %}"><span class="glyphicon glyphicon-log-in"></span> Register/Login</a></li>
          {% endif %}
              
            
          </ul>
      </div>
  </nav>
  </div>
  <br><br><br> 

{% block body %}
{% endblock %}


</body>
</html>

mywebsite/templates/base_events.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
  <title>WEBSITE</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="icon" href="https://yantragene.co.in/images/minLogo.png" type="image/jpg" sizes="16x16">
  <link rel="stylesheet" type="text/css" href="style.css">
  <script type="text/javascript" src={% static "js/base_events.js" %}></script>

   <style type="text/css">
    #event_name{
      color:aquamarine;
      font-family:cursive ;
      font-size:6vw;
    }
   #heading_row{
    height:40px;
   }
   #desc_div,#rule_div,#coord_div,#cord_div,#reg_div{
    background-color: white;
    border-radius: 5px;
   }
   .topics{
      color:#F0B27A;
      font-size:30px;
      text-align:center;
      cursor:pointer;
    }
    .topics:hover{
      color:#F8F9F9;
    }
    body{
      background-color:#110E0B;
    }
    .cross{
      height:25px;
      width:25px;
      margin-left: 98%;
      float:left;
    }
    #desc_div{
      display:block;
    }
     #rule_div,#coord_div,#cord_div,#reg_div{
      display:none;
    }
  </style>

  {% block head %}
  {% endblock %}
  
  </head>
  <body>

    <center><h1 id="event_name">{{ eve }}</h1></center>

    <div class="container-fluid">
        <div id="heading_row" class="row">
            <div class="col-md-3 col-sm-10">
              <div>
                <h2 class="topics" id="desc_btn">Description</h2>
            </div>
       </div>
            <div class="col-md-3 col-sm-10">
              <div>
                <h2 class="topics" id="rules_btn">Rules And Regulations</h2>
            </div>
       </div>
            <div class="col-md-3 col-sm-10">
              <div>
                <h2 class="topics" id="cord_btn">Co-Ordinator</h2>
            </div>
       </div>
            <div class="col-md-3 col-sm-10">
              <div>
                <h2 class="topics" id="reg_btn">Register</h2>
            </div>
       </div>
      </div>

      <div class="row">
    
          <div id="desc_div"class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3 col-sm-12 ">
            <img class="cross" src="{% static 'images/cross.png' %}">
            <center><h3>Description</h3></center>
            {% block desc %}
            {% endblock %}
          </div>

<!--        -------          -----  RULES ---------                        -->

           <div id="rule_div"class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">
             <img class="cross" src="{% static 'images/cross.png' %}">
            <center><h3>Rules</h3></center>
            {% block rules %}
            {% endblock %}
          </div>
 

      <div id="cord_div"class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">
        <img class="cross" src="{% static 'images/cross.png' %}">
        <center><h3>Coordinators</h3></center><br>
           {% if coord %}
                <div class="row">
 
                {% for c in coord %} 
                   <div class="col-md-6 col-sm-8">
                    <center>
                            <img src="{{ c.cimage.url}}" alt="{{ c.cname }}" class="img-thumbnail img-responsive" style="height:200px;width:200px;"><br><br>
                             <p><b>{{ c.cname }}</b></p>
                              <p><span class="glyphicon glyphicon-phone"><b> {{ c.cmobile }} </b></span></p>
                              <p><span class=" glyphicon glyphicon-envelope"><b> {{ c.cemail }} </b></span></p></center>
                   </div>             
               {% endfor %}      

               </div>
           {% else %}
             <h1>No details for now</h1>
           {% endif %} 
      </div>
       

       <div id="reg_div"class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3 col-sm-10 col-sm-offset-1">
        <img class="cross" src="{% static 'images/cross.png' %}">
        <center><h3>Register</h3></center>
        {% block reg %}
        {% endblock %}

  </div>
</div>
</body>
</html>

mywebsite/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

<script type="text/javascript" src="{% static 'js/contact.js' %}"></script>

<style>
		.mapouter{
			text-align:right;
			height:500px;
			width:600px;
		}
		.gmap_canvas {overflow:hidden;
			background:none!important;
			height:500px;
			width:600px;
		}
		#content{
			color:#D0D3D4;
			border:2px solid #D0D3D4;
			border-radius: 5px;
			font-size:15px;
			
		}
		p{
			font-family: cursive;
		}
	</style>

{% endblock %}

{% block body %}
<h1 style="color:aquamarine;text-align: center;font-family: cursive;font-size: 4.5vw;">REACH US</h1>
	<div class="container">
		<div class="row">			
			<div class="col-md-6 col-sm-8">
			<div class="mapouter">
				<div class="gmap_canvas">
					<iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=feroze%20gandhi%20institute%20raebareli&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
					<a href="https://www.maps-erstellen.de">maps-erstellen.de</a>
				</div>
			</div>
		</div>

		<div class="col-md-5 col-md-offset-1 col-sm-10" id="content">
			<p><b>Call us on</b> :8318203223 </p>
			<p><b>Mail us at</b> : fest@yantragene.com</p>
			<p><b>Official Website is</b> : <a href="https://fgiet.ac.in">fgiet.ac.in</a></p>
			<p>Feroze Gandhi Institute Of Engineering AndTechnology,</p>
			<p>Lucknow Road, Near Ratapur Chauraha,</p> 
			<p>Ratapur, Raebareli,</p>
			<p>Uttar Pradesh 229316, India</p>
			
			<center><h3>Feedback Please</h3></center>
			<form action="{% url 'contact:contact' %}" method="get">
				{{form}}
				<br>
				<center>
					<input type="submit" value="Send" class="btn btn-default btn-small btn-success" onclick="alert('We apppreciate your suggestion')">
					<input type="reset" value="Reset" class="btn btn-default btn-small btn-info">
				</center>
			</form>
		</div>
		</div>
	</div>

{% endblock %}

mywebsite/templates/events.html
{% extends 'base.html' %}
{% block head %}
{% load static %}


<style type="text/css">
    .dept_box{
      height:450px;
    }
    h1{
        font-size: 6vw;
    }
</style>

<script type="text/javascript" src="{% static 'js/events.js' %}"></script>

{% endblock %}
{% block body %}

  <div class="container">
    <center><h3 style="color:red;">{{ msg }}</h3><center>
    <h1 style="color:aquamarine;text-align: center;font-family: cursive;">EVENTS</h1><br>
    <div class="row">      
        {% if outer_event %}
            {% for d,elist in outer_event.items %}

               <div class="col-md-6 col-lg-3 col-sm-10">
                <div class="thumbnail dept_box">

                    <img src="{{ d.bimage.url }}" alt="{{ d.branch }}" style="width:100%;height:250px;">
                    <div class="caption">
                        <center><h3>{{ d.branch }}</h3></center>
                    </div>
                    <ul class="list-unstyled">
                    {% for e in elist %}
                        <center><li><p><a href="{% url 'events:details' id=e.id %}">{{e.event}}</a></p></li></center>
                    {% endfor %} 
                    </ul>               
                </div>
            </div>
          {% endfor %}
        {% else %}
            <h1>No Proper Data</h1>
        {% endif %} 
{% endblock %}
</div>
</div>

mywebsite/templates/gallery.html
{% extends 'base.html' %}
{% block head %}
{% load static  %}

<script type="text/javascript" src="{% static 'js/gallery.js' %}"></script>
<style type="text/css">
	h1{
	color:aquamarine;
	font-family:cursive;
	font-size: 5vw;
}
</style>

{% endblock %}

{% block body %}

<center ><h1>GALLERY</h1></center>
	<br><br>
	{% if images %}
	<div class="container">
	<div class="row">
		{% for i in images %}
	    <div class="col-md-4 col-sm-10">
	        <div class="thumbnail image">
	      
				<a href="{{ i.image.url }}">
		        	<center><img src="{{ i.image.url }}" alt="{{ i.imgid }}" style="width:100%;"></center>
		    	</a>
	     
		
	        </div>
	    </div>
	  {% endfor %}
	</div>
	</div>
    {% else %}
    	<center><h1>NO DATA NOW</h1></center>
    {% endif %}
















{% endblock %}

mywebsite/templates/notify.html
{% extends 'base.html' %}
{% block head %}
{% load static %} 
 <style type="text/css">
          
          #notes{
              border:1px solid yellow;
              border-left:6px solid yellow;
          }	
        .panel-height {
             height:100%; / change according to your requirement/
             
          }
          .underline_text {
              text-align: center;
              font-size:5.7vw;
              color:aquamarine;
              font-family: cursive;
          }
          p{
            font-family: serif;
            text-align: center;
          }
          .container-border{
             border: 1px solid #CA6F1E;
            border-radius: 15px;  
          }

 </style>

 <script type="text/javascript" src=" {% static 'js/notify.js' %}"></script>

{% endblock %}

{% block body %}
     <h1 class="underline_text">NOTIFICATIONS</h1><br><br>
     <div class="container-fluid">
     <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-info">
         <div class="panel-body panel-height" style="background-color:white;">
          <ul class="head list-unstyled" style="font-size: 22px;">

                     <li><p class="container-border">FGIET will provide accommodation to the students for free.</p>
                    <li><p class="container-border">Lunch and dinner will be provided by the college at Rs. 40 per diet.</p></li>
                    <li><p class="container-border">winners and runners-up of each events will receive a cash prize.</p></li>
          </ul>
         </div>
      </div>       
     </div>
  </div>
</div>  
{% endblock %}